export const endPoints = {
  login: "auth/local",
  regiter: "auth/local/register",
  forgotPassword: "",
  resetPassword: "",
  loginWithGoogle: "connect/google",
  loginWithFaceBook: "connect/facebook",
  services: "services",
  userSlot: "user-slots",
  createSlot: "slots",
  faqs: "faqs",
  articles: "articles",
  contactUs: "contact-uses",
  myData: "users/me",
  discounts: "discounts",
};
