export const endPoints = {
  login: "auth/local",
  regiter: "auth/local/register",
  forgotPassword: "",
  resetPassword: "",
  loginWithGoogle: "connect/google",
  loginWithFaceBook: "connect/facebook",
  services: "services",
  userSlot: "user-slots",
  contactUs: "contact-uses",
  myData: "users/me",
  updateMyData: "users",
  discounts: "discounts",
  login: "auth/local",
  register: "auth/local/register",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  loginWithGoogle: "connect/google",
  loginWithFaceBook: "connect/facebook",
  services: "services",
  createSlot: "slots",
  faqs: "faqs",
  articles: "articles",
  contactUs: "contact-us",
  rateReview: "rate-and-reviews",
};
