import Head from "next/head";
import React, { useEffect, useContext } from "react";
import { useRouter } from "next/router";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
import Banner from "@/src/components/pages/Home/bannerSeection/bannerSection";
import Testimonals from "@/src/components/pages/Home/testimonals/Testimonals";
import PromiseSection from "@/src/components/pages/Home/promise/PromiseSection";
import BodyService from "@/src/components/pages/Home/bodyService/BodyService";
import { bookingContext } from "@/store/bookingContext";
import { consultationContext } from "@/store/consultationContext";
import { discountPercentContext } from "@/store/discountPercentContext";
import { userContext } from "@/store/userContext";
import Progressbar from "@/src/components/pages/Home/bodyService/Progressbar";
import DiscountToggle from "@/src/components/pages/Home/bodyService/DiscountToggle";
import DiscountType from "@/src/components/pages/Home/bodyService/DiscountType";
import styles from "@/styles/components/bodyService/bodyService.module.css";
import { createAPIEndPoint } from "@/src/config/api";
import { endPoints } from "@/src/config/endpoints";
import { referralDiscount } from "@/store/referralDiscount";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [discountPercent, setDiscountPercent] = useContext(
    discountPercentContext
  );
  const [booking, setBooking] = useContext(bookingContext);
  const [consultation, setConsultation] = useContext(consultationContext);
  const [user, setUser] = useContext(userContext);
  const [referral, setReferral] = useContext(referralDiscount);
  const getUserData = async () => {
    try {
      const response = await createAPIEndPoint(
        endPoints.myData,
        true
      ).fetchAllWithToken();
      console.log(response.data.user_slots, "response");
      setUser(response.data);

      const details = response.data.user_slots.map((item) => item.details);
      setUser(response.data);
      console.log(response.data.isReferred, "userddddd");
      if (response.data.isReferred) {
        setReferral(true);
      }
      if (details.length) {
        details.forEach((element) => {
          setBooking(element);
        });
        setConsultation(false);
      } else {
        setConsultation(true);
      }
      console.log(details, "ddddd");
    } catch (error) {
      console.log(error, "error");
    }
  };

  useEffect(() => {
    getUserData();
  }, []);

  return (
    <>
      <Head>
        <title>Everly Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <PromiseSection />
      <BodyService />
      <div className={styles.bodyServiceContainer}>
        <div className={styles.bodyServiceWrapper}>
          <div className={styles.progressbarContainer}>
            <div className={styles.progressbarSection}>
              <Progressbar discountPercent={discountPercent} />
              <DiscountToggle />
              <DiscountType />
            </div>
          </div>
        </div>
      </div>
      <Testimonals />
    </>
  );
}
