import Head from "next/head";
import React, { useEffect, useRef } from "react";
import { useRouter } from "next/router";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/src/components/pages/Home/bannerSeection/bannerSection";
import Testimonals from "@/src/components/pages/Home/testimonals/Testimonals";
import PromiseSection from "@/src/components/pages/Home/promise/PromiseSection";
import BodyService from "@/src/components/pages/Home/bodyService/BodyService";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const bodyRef = useRef();
  const paramValue = router.query.isGoToService;

  useEffect(() => {
    if (paramValue) {
      // document.getElementById("body").scrollTo({ y: 100, behavior: "smooth" });
      // bodyRef.current.scrollTo({ behavior: "smooth" });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Everly Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <PromiseSection />
      <BodyService ref={bodyRef} id="body" />
      <Testimonals />
    </>
  );
}
